
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =             264
     no. of nonzeroes in lower triangle of a =            3228
     no. of nonzeroes in the factor l        =            6896
     ratio of nonzeroes in factor (min/max)  =          0.5568
     number of super nodes                   =              16
     maximum order of a front matrix         =              30
     maximum size of a front matrix          =             465
     maximum size of a front trapezoid       =             465
     METIS reordering method used 
     no. of floating point ops for factor    =      8.9684D+04
     no. of floating point ops for solve     =      1.7040D+04
     ratio of flops for factor (min/max)     =          0.5700
     ratio of allocated memory (max/min)     =          1.0531
     number of positive pivots               =             264
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000051
     time (cpu & wall) for ordering          =        0.000000        0.000552
     time (cpu & wall) for other matrix prep =        0.000000        0.000837
     time (cpu & wall) for value input       =        0.000000        0.000029
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001288

     no input or output performed

  Solver Memory allocated on core    0       =        0.325 MB
  Solver Memory allocated on core    1       =        0.318 MB
  Solver Memory allocated on core    2       =        0.312 MB
  Solver Memory allocated on core    3       =        0.308 MB
  Total Solver Memory allocated by all cores =        1.263 MB

